version: "2"

services:
  sqlserver:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=G00don3!
      - MSSQL_PID=Standard
    restart: unless-stopped
    networks:
      devnet:
        aliases:
          - sqlserver

networks:
  devnet: